web:
  image: nginx:latest
  ports:
    - 8080:80
  volumes:
    - ./client:/var/www/html
    - ./Docker/nginx/client.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  image: php:7.2-fpm
  ports:
    - 9000:9000
  volumes:
    - ./client:/var/www/html